name: Android Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
          echo "APK généré :"
          find "$PWD" -name "*.apk"

      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: android/app/build/outputs/apk/debug/*.apk
