name: Android Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Find and Build
        run: |
          # Méthode qui a marché pour vous
          GRADLE_DIR=$(find . -name "gradlew" -exec dirname {} \; | head -1)
          echo "Dossier Gradle trouvé : $GRADLE_DIR"
          cd "$GRADLE_DIR"
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
          echo "APK généré dans :"
          find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: magic-control-app
          path: |
            */build/outputs/apk/debug/*.apk
            */*/build/outputs/apk/debug/*.apk
