name: Android Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          ANDROID_DIR=$(find . -name "build.gradle" -exec dirname {} \; | grep -v "node_modules" | head -1)
          cd "$ANDROID_DIR"
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
          echo "APK généré à :"
          find . -name "*.apk"
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: |
            */build/outputs/apk/debug/*.apk
            */*/build/outputs/apk/debug/*.apk
